# Meta Learning Cache Replacement Policy

## Decompress tar.gz

**Don't run unless you have a lot of storage!**

In [ ]:
import argparse
import os


EXTENSION = '.tar.gz'
BLKPARSE = '.blkparse'


def main(input_dir, output_dir):
  assert os.path.isdir(input_dir), "The input directory {} does not exist".format(input_dir)

  input_dir = input_dir.rstrip("/")
  if not os.path.isdir(output_dir):
    print("Creating output directory {}".format(output_dir))
    os.mkdir(output_dir)

  for file in os.listdir(input_dir):
    if not file.endswith(EXTENSION):
      continue
    
    print("Extracting and moving {}".format(file))
    execute_command("tar -xvzf {}".format(input_dir + '/' + file))
    execute_command("mv ./*{} {}".format(BLKPARSE, output_dir))
    

def execute_command(command):
  os.system(command)



In [ ]:
input_dir = "FIU_raw"
output_dir = "FIU_trace"
main(input_dir, output_dir)

## Install Dependency

In [122]:
import sys
import random
import numpy as np
import pandas as pd
from tqdm import tqdm_notebook as tqdm 
from collections import Counter, deque, defaultdict
from sklearn import preprocessing
from sklearn.preprocessing import normalize
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.neural_network import MLPClassifier
import tensorflow as tf
import pickle


## Block Cache Model

### Global Variable

In [123]:
# Maximum block number
maxpos = 1000000000000

# Number of features (Recency, Frequency, Block No.)
num_params = 3

# Cache Size
cache_size = 10

# Sequence Length
sequence_length = 5

# Storage
sequence_data = np.zeros((sequence_length, cache_size, num_params))

# How often to store the data (Removed currently)
sampling_freq = cache_size

# How many % of cache to use
eviction = int(0.7 * cache_size)  

# Results
lruCorrect = 0
lruIncorrect = 0

lfuCorrect = 0
lfuIncorrect = 0

# Variables
X = np.array([], dtype=np.int64).reshape(0,num_params)
Y = np.array([], dtype=np.int64).reshape(0,1)

### Load workload
**cheetah.cs.fiu.edu-110108-113008.1.blkparse** does not contain correct data.

In [124]:
# train = "FIU_trace/cheetah.cs.fiu.edu-110108-113008.2.blkparse"
train = "FIU_trace/casa-110108-112108.1.blkparse"

df = pd.read_csv(train, sep=' ',header = None)
df.columns = ['timestamp','pid','pname','blockNo', \
              'blockSize', 'readOrWrite', 'bdMajor', 'bdMinor', 'hash']

trainBlockTrace = df['blockNo'].tolist()
trainBlockTrace = trainBlockTrace[:int(len(trainBlockTrace)*0.5)]
# trainBlockTrace = trainBlockTrace[:300]
len(trainBlockTrace)

486357

### Data Preprocessing and Data Construction

In [125]:
# Taken from Shehbaz
def get_recency(lru, cache):
    recency = []
    recency_dict = defaultdict(int)
    
    # Compute the recency order of each page in cache
    for time in range(len(lru)):
        recency_dict[lru[time]] = time + 1
        
    for block in cache:
        recency.append(recency_dict[block])

    return recency

def get_frequency(lfu, cache):
    frequency = []
    
    for block in cache:
        frequency.append(lfu[block])
    return frequency

def normalize_columns(input):
    return normalize(input, axis=0)

In [126]:
def get_single_length_input(lfu, lru, cache, preprocess_func, cache_size):
    input_recency = get_recency(lru, cache)
    input_frequency = get_frequency(lfu, cache)
    input_block_num = cache[:]
    
    if len(input_recency) < cache_size:
        for i in range(0, cache_size - len(input_recency)):
            input_recency.append(0)
            input_frequency.append(0)
            input_block_num.append(0)
    
    # Columns: recency, frequency, block number
    # Row: cache location
    raw_input = np.column_stack((input_recency, input_frequency, input_block_num))
    
    return preprocess_func(raw_input)


SEQ_DIM = 0
def get_multiple_length_input(sequence_length, prev_inputs, lfu, lru, cache, preprocess_func, cache_size):
    assert prev_inputs.shape[SEQ_DIM] == sequence_length
    current_input = get_single_length_input(lfu, lru, cache, preprocess_func, cache_size)
    return np.vstack((prev_inputs[1:], current_input[None]))
    

def get_outputs(cache, delete):
    assert(len(cache) == len(delete))
    Y_current = []
    KV_sorted = Counter(delete)
    evict_dict = dict(KV_sorted.most_common(eviction))
    assert(len(evict_dict) == eviction)
    all_vals = evict_dict.values()
    for e in cache:
        if e in evict_dict.values():
            Y_current.append(1)
        else:
            Y_current.append(0)

    assert(Y_current.count(1) == eviction)
    assert((set(all_vals)).issubset(set(cache)))
    return Y_current


def store_pair(request_time, seq_len, seq_data, lfu, lru, cache, deleted, cache_size, preprocess_func):
    global X,Y,Z
    cache = list(cache)
    Y_current = get_outputs(cache, deleted)
    
    Y = np.vstack((Y, np.array(Y_current)[None]))
    X = np.vstack((X, seq_data[None]))
    Z = np.vstack((Z, request_time))

    assert(Y_current.count(1) == eviction)
    return Y_current

### Belady Optimal Algorithm (From Shehbaz)

In [127]:
def belady_opt(blocktrace, frame):
    global maxpos, sequence_data, sequence_length
    
    optimal = defaultdict(deque)
    deleted = defaultdict(int)
    lfu = defaultdict(int)
    lru = []

    # Build the whole index for finding optimal eviction ordering
    for request_time, block in enumerate(tqdm(blocktrace, desc="OPT: building index")):
        optimal[block].append(request_time)

    hit, miss = 0, 0

    cache = []
    
    for request_time, block in enumerate(tqdm(blocktrace, desc="OPT")):
        old_seq = sequence_data[:]
        # increase frequency count
        lfu[block] +=1

        # Remove the block i at time step j from the index
        if len(optimal[block]) is not 0 and optimal[block][0] == request_time:
            optimal[block].popleft()

        
        if block in cache:
            # Cache Hit
            # Update block to MRU position
            hit += 1
            lru.remove(block)
            lru.append(block)
            
            assert request_time in deleted
            
            del deleted[request_time]
            if len(optimal[block]) is not 0:
                deleted[optimal[block][0]] = block
                optimal[block].popleft()
            else:
                deleted[maxpos] = block
                maxpos -= 1
            sequence_data = get_multiple_length_input(sequence_length, sequence_data, lfu, lru, cache, lambda x: x, cache_size)
        else:
            # Cache Miss
            miss += 1
            if len(cache) == frame:
                # Cache is full
                assert(len(deleted) == frame)
                evictpos = max(deleted)
                
                #if (seq_number % sampling_freq +1 == sampling_freq):
                y_opt = store_pair(request_time, sequence_length, sequence_data, lfu, lru, cache, deleted, cache_size, lambda x: x)
    
                cache[cache.index(deleted[evictpos])] = block
                lru.remove(deleted[evictpos])
                del deleted[evictpos]
            else:
                # Cache isn't full
                cache.append(block)                
            
            # Add the candidate victim page to the j'th time step
            if len(optimal[block]) is not 0:
                deleted[optimal[block][0]] = block
                optimal[block].popleft()
            else:
                deleted[maxpos] = block
                maxpos -= 1
            lru.append(block)
            sequence_data = get_multiple_length_input(sequence_length, sequence_data, lfu, lru, cache, lambda x: x, cache_size)


    hitrate = hit / (hit + miss)

    return hitrate

## Generate training data

In [ ]:
X = np.array([], dtype=np.int64).reshape(0, sequence_length, cache_size, num_params)
Y = np.array([], dtype=np.int64).reshape(0, cache_size)
Z = np.array([], dtype=np.int32).reshape(0, 1)
trainHitrate = belady_opt(trainBlockTrace, cache_size)
X_train = X
Y_train = Y

# training_data_file = 'fiu_01.pkl'
training_data_file = 'home_1_1.pkl'
with open(training_data_file, 'wb+') as f:
    pickle.dump([X, Y, Z], f)

In [102]:
with open(training_data_file, 'rb') as f:
    x, y, z = pickle.load(f)
    
#    for i, v in enumerate(x):
#        if i + 1 == x.shape[0]:
#            continue
#        print(np.array_equal(x[i], x[i + 1]))
#    print(x[-2, -2] == x[-2,-1])
    print(z[5])
    print(x[5])
    print(x.shape)
    print(y.shape)


[18]
[[[7.00000000e+00 1.00000000e+00 5.08455712e+08]
  [1.00000000e+00 1.00000000e+00 5.08516672e+08]
  [2.00000000e+00 1.00000000e+00 5.08516680e+08]
  [3.00000000e+00 1.00000000e+00 5.08516688e+08]
  [8.00000000e+00 1.00000000e+00 5.08455720e+08]
  [9.00000000e+00 1.00000000e+00 5.08500288e+08]
  [1.00000000e+01 1.00000000e+00 5.08500296e+08]
  [4.00000000e+00 1.00000000e+00 5.19854400e+08]
  [5.00000000e+00 1.00000000e+00 4.88846200e+08]
  [6.00000000e+00 1.00000000e+00 5.08455704e+08]]

 [[6.00000000e+00 1.00000000e+00 5.08455712e+08]
  [1.00000000e+00 1.00000000e+00 5.08516672e+08]
  [2.00000000e+00 1.00000000e+00 5.08516680e+08]
  [3.00000000e+00 1.00000000e+00 5.08516688e+08]
  [7.00000000e+00 1.00000000e+00 5.08455720e+08]
  [8.00000000e+00 1.00000000e+00 5.08500288e+08]
  [9.00000000e+00 1.00000000e+00 5.08500296e+08]
  [1.00000000e+01 1.00000000e+00 5.08500304e+08]
  [4.00000000e+00 1.00000000e+00 4.88846200e+08]
  [5.00000000e+00 1.00000000e+00 5.08455704e+08]]

 [[5.000000

#### Sample test

In [ ]:
lfu = {2: 1, 3: 2, 4: 1}
lru = [2, 3, 4]
cache = [3, 2, 4]
hidden = np.zeros((5, 3, 3))

hidden = get_multiple_length_input(5, hidden, lfu, lru, cache, lambda x: x)
print(hidden)
hidden = get_multiple_length_input(5, hidden, lfu, lru, cache, normalize_columns)
print(hidden)

In [ ]:
blocktrace = trainBlockTrace
OPT = defaultdict(deque)
for i, block in enumerate(tqdm(blocktrace, desc="OPT: building index")):
        OPT[block].append(i)
OPT